data_path: /checkpoint/maui/shared/datasets/airs_text_only_prepared/TimeSeriesForecastingKaggleWebTrafficMASE
description:
  label_target:
    _type: List
    feature:
      _type: Value
      dtype: float64
  target:
    _type: List
    feature:
      _type: Value
      dtype: float32
is_local: true
name: monash_tsf
