metric_lower_is_better: true
file_export_globs:
  - submission.csv
container_python_requirements:
  - datasets==4.0.0
evaluate_container_python_requirements:
  - datasets==4.0.0
  - torchmetrics
  - pandas
  - numpy
  - torch
logging_info:
  name: GraphRegressionZincMae
  dataset: graphs-datasets/ZINC
  category: Molecules and Proteins ML
  research_problem: Graph Regression
  output_type: Text Generation
  config: default
  train_split: train
  test_split: test
  input_columns:
    - x
    - node_feat
    - edge_index
    - edge_attr
    - num_nodes
  scoring_column: y
  shape: 
   - 5000
  custom_gold_labels: false
  custom_rad_class: false
  metric: MAE
  additional_metrics: null
  sota:
    - sota_paper_title: 'An end-to-end attention-based approach for learning on graphs'
      sota_paper_url: https://arxiv.org/pdf/2402.10793v2
      sota_score: 0.017
      sota_year: 2024
      sota_venue: Nature Communications
  dataset_paper_url: https://pubs.acs.org/doi/10.1021/ci049714+
  estimated_worst_score: 9.699923627
  optimal_score: 0.0
