data_path: /checkpoint/maui/shared/datasets/airs_text_only_prepared/CodeRetrievalCodeXGlueMRR
description:
  id:
    _type: Value
    dtype: int32
  query:
    _type: Value
    dtype: string
is_local: true
name: code_x_glue_tc_nl_code_search_adv
