metric_lower_is_better: true
file_export_globs:
  - submission.csv
container_python_requirements:
  - datasets==4.0.0
evaluate_container_python_requirements:
  - datasets==4.0.0
  - torchmetrics
  - pandas
  - numpy
  - torch
  - scikit-learn
logging_info:
  name: TimeSeriesForecastingSolarWeeklyMAE
  category: Time Series
  research_problem: Time Series Forecasting
  output_type: Numeric
  dataset: Monash-University/monash_tsf
  config: solar_weekly
  metric: MAE
  additional_metrics: MAPE, sMAPE, MAE, RMSE
  train_split: train
  test_split: test
  input_columns:
    - target
  scoring_column: 
    - label_target
  shape: (137,)
  custom_gold_labels: true
  custom_rad_class: false
  sota:
    - sota_paper_title: 'In-Context Fine-Tuning for Time-Series Foundation Models'
      sota_paper_url: https://arxiv.org/pdf/2410.24087
      sota_score: 576.35
      sota_year: 2025
      sota_venue: ICML
  dataset_paper_url: https://arxiv.org/abs/2105.06643
  estimated_worst_score: 627933888720355
  optimal_score: 0.0
