data_path: /checkpoint/maui/shared/datasets/airs_text_only_prepared/QuestionAnsweringDuoRCAccuracy
description:
  answers:
    _type: List
    feature:
      _type: Value
      dtype: string
  no_answer:
    _type: Value
    dtype: bool
  plot:
    _type: Value
    dtype: string
  plot_id:
    _type: Value
    dtype: string
  question:
    _type: Value
    dtype: string
  title:
    _type: Value
    dtype: string
is_local: true
name: duorc
