data_path: /checkpoint/maui/shared/datasets/airs_text_only_prepared/R2AbsMolecularPropertyPredictionQm9MeanAbsoluteError
description:
  A:
    _type: Value
    dtype: float32
  B:
    _type: Value
    dtype: float32
  C:
    _type: Value
    dtype: float32
  R_2_Abs:
    _type: Value
    dtype: float32
  atomic_numbers:
    _type: List
    feature:
      _type: Value
      dtype: int64
  composition:
    _type: List
    feature:
      _type: Value
      dtype: int64
  id:
    _type: Value
    dtype: string
  natoms:
    _type: Value
    dtype: int64
  pos:
    _type: List
    feature:
      _type: List
      feature:
        _type: Value
        dtype: float32
  tags:
    _type: List
    feature:
      _type: Value
      dtype: int64
is_local: true
name: qm9
