data_path: /checkpoint/maui/shared/datasets/airs_text_only_prepared/QuestionAnsweringEli5Rouge1
description:
  answers:
    a_id:
      _type: List
      feature:
        _type: Value
        dtype: string
    score:
      _type: List
      feature:
        _type: Value
        dtype: int64
    text:
      _type: List
      feature:
        _type: Value
        dtype: string
  answers_urls:
    _type: List
    feature:
      _type: List
      feature:
        _type: Value
        dtype: string
  document:
    _type: Value
    dtype: string
  q_id:
    _type: Value
    dtype: string
  selftext:
    _type: Value
    dtype: string
  selftext_urls:
    _type: List
    feature:
      _type: Value
      dtype: string
  subreddit:
    _type: Value
    dtype: string
  title:
    _type: Value
    dtype: string
  title_urls:
    _type: List
    feature:
      _type: Value
      dtype: string
  url:
    _type: Value
    dtype: string
is_local: true
name: eli5
